security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username 
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: menu
            pattern:    ^/
            http_basic: ~
            anonymous: ~
    
    access_control:
        # Les regles de securité
        # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
        # peuvent acceder à toutes les pages commençant par /admin
       
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }    
        - { path: ^/, roles: ROLE_USER }
        
        