security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username 
                
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: menu
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
   
    
    access_control:
        # Les regles de securité
        # Là dans ce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
        # peuvent acceder à toutes les pages commençant par /admin
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/, roles: ROLE_ADMIN }